stages:
    - build
    - deploy to production

variables:
    APP_VERSION: $CI_PIPELINE_IID

build website:
    image: node:16-alpine
    stage: build
    script:
        - npm install
    artifacts:
        paths:
            - public

.deploy:
    image:
        name: amazon/aws-cli:2.4.11
    script:
        - aws --version
        - aws s3 rm s3://$AWS_S3_BUCKET --recursive
        - aws s3 cp public s3://$AWS_S3_BUCKET --recursive

deploy to production:
    environment: production
    when: manual
    stage: deploy to production
    extends: .deploy
