stages:
    - build
    - deploy to production

variables:
    APP_VERSION: $CI_PIPELINE_IID

build website:
    image: node:16-alpine
    stage: build
    script:
        - npm install
    artifacts:
        paths:
            - build

.deploy:
    image:
        name: amazon/aws-cli:2.4.11
        entrypoint: [""]
    rules: 
        - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_REF_NAME
    script:
        - aws --version
        - aws s3 sync build s3://$AWS_S3_BUCKET --delete

deploy to production:
    environment: production
    when: manual
    stage: deploy to production
    extends: .deploy
